# PR Auto-Labeler Configuration
# Maps changed file paths to product/domain/tool labels (DDD taxonomy)
# Cross-cutting paths (lib/schemas/**, docs/**, components/ui/**) deliberately unmapped

'product/quotes':
  - changed-files:
      - any-glob-to-any-file: 'app/(dashboard)/quotes/**'

'product/jobs':
  - changed-files:
      - any-glob-to-any-file: 'app/(dashboard)/jobs/**'

'product/customers':
  - changed-files:
      - any-glob-to-any-file: 'app/(dashboard)/customers/**'

'product/invoices':
  - changed-files:
      - any-glob-to-any-file: 'app/(dashboard)/invoices/**'

'domain/garments':
  - changed-files:
      - any-glob-to-any-file: 'app/(dashboard)/garments/**'

'domain/pricing':
  - changed-files:
      - any-glob-to-any-file: 'app/(dashboard)/settings/pricing/**'

'domain/colors':
  - changed-files:
      - any-glob-to-any-file: 'app/(dashboard)/settings/colors/**'

'tool/work-orchestrator':
  - changed-files:
      - any-glob-to-any-file: 'scripts/**'

'tool/knowledge-base':
  - changed-files:
      - any-glob-to-any-file: 'knowledge-base/**'

'tool/pm-system':
  - changed-files:
      - any-glob-to-any-file:
          - 'config/**'
          - '.github/**'
