name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug] "
labels: ["type/bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug clearly
      placeholder: What did you observe?
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What should have happened instead?
      placeholder: Describe the correct behavior
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this?
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. See error
    validations:
      required: true

  - type: dropdown
    id: product-tool
    attributes:
      label: Product/Tool
      description: Which product or tool is affected?
      # Sync with config/products.json + config/tools.json
      options:
        - Dashboard
        - Quotes
        - Customers
        - Invoices
        - Jobs
        - Garments
        - Screens
        - Pricing
        - Work Orchestrator
        - Skills Framework
        - Agent System
        - Knowledge Base
        - CI Pipeline
        - PM System
    validations:
      required: true

  - type: input
    id: url-route
    attributes:
      label: URL / Route
      description: Which page or route does this occur on?
      placeholder: "e.g., /quotes/new, /dashboard"
    validations:
      required: false

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser were you using?
      options:
        - Chrome
        - Safari
        - Firefox
        - Edge
        - Other
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Console Errors
      description: Paste screenshots or browser console output here
      placeholder: Drag and drop screenshots or paste console errors
    validations:
      required: false

  - type: textarea
    id: files-to-read
    attributes:
      label: Files to Read
      description: Entry points for agents picking up this bug
      render: text
      placeholder: |
        app/(dashboard)/quotes/page.tsx
        lib/schemas/quote.ts
    validations:
      required: false

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical
        - High
        - Normal
        - Low
    validations:
      required: false
