name: Research Task
description: Investigate a question or explore a technical approach
title: '[Research] '
labels: ['type/research']
body:
  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: What are we trying to learn?
      placeholder: Describe the knowledge gap or decision to be made
    validations:
      required: true

  - type: textarea
    id: questions
    attributes:
      label: Questions
      description: Specific questions to answer
      placeholder: |
        1. How does X work?
        2. What are the trade-offs between A and B?
        3. Is Y feasible given our constraints?
    validations:
      required: true

  - type: dropdown
    id: product-domain-tool
    attributes:
      label: Product / Domain / Tool
      description: Which product, domain, or tool does this relate to?
      # Sync with config/products.json + config/tools.json
      options:
        - Product: Dashboard
        - Product: Quotes
        - Product: Customers
        - Product: Invoices
        - Product: Jobs
        - Product: Garments
        - Product: Screens
        - Domain: Garments
        - Domain: Screens
        - Domain: Pricing
        - Domain: Colors
        - Domain: Direct-to-Film
        - Domain: Screen Printing
        - Domain: Mobile
        - Tool: Work Orchestrator
        - Tool: Skills Framework
        - Tool: Agent System
        - Tool: Knowledge Base
        - Tool: CI Pipeline
        - Tool: PM System
        - Tool: Database
      required: true

  - type: dropdown
    id: deliverable
    attributes:
      label: Expected Deliverable
      description: What artifact should this research produce?
      options:
        - Spike doc (docs/spikes/)
        - KB session doc
        - Issue comment with findings
        - Decision recommendation
        - Proof of concept branch
    validations:
      required: false

  - type: textarea
    id: files-to-read
    attributes:
      label: Files to Read
      description: Entry points for agents picking up this issue
      render: text
      placeholder: |
        docs/shaping/topic/shaping.md
        lib/schemas/relevant.ts
    validations:
      required: false
