name: Research Task
description: Investigate a question or explore a technical approach
labels: ["type/research"]
body:
  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: What are we trying to learn?
      placeholder: Describe the knowledge gap or decision to be made
    validations:
      required: true

  - type: textarea
    id: questions
    attributes:
      label: Questions
      description: Specific questions to answer
      placeholder: |
        1. How does X work?
        2. What are the trade-offs between A and B?
        3. Is Y feasible given our constraints?
    validations:
      required: true

  - type: dropdown
    id: product-tool
    attributes:
      label: Product/Tool
      description: Which product or tool does this relate to?
      options:
        - Dashboard
        - Quotes
        - Customers
        - Invoices
        - Jobs
        - Garments
        - Screens
        - Pricing
        - Work Orchestrator
        - Skills Framework
        - Agent System
        - Knowledge Base
        - CI Pipeline
    validations:
      required: true

  - type: textarea
    id: files-to-read
    attributes:
      label: Files to Read
      description: Entry points for agents picking up this issue
      placeholder: |
        - `docs/shaping/topic/shaping.md`
        - `lib/schemas/relevant.ts`
    validations:
      required: false
