name: Tracking Issue
description: Track a multi-part effort with sub-issues
title: "[Tracking] "
labels: ["type/tooling"]
body:
  - type: markdown
    attributes:
      value: |
        Tracking issues coordinate multi-part efforts. After creating this issue,
        add sub-issues via GitHub's sub-issue feature rather than task-list checkboxes.

  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: What does completion look like?
      placeholder: Describe the end state when all sub-issues are resolved
    validations:
      required: true

  - type: textarea
    id: sub-issues
    attributes:
      label: Sub-issues planned
      description: List planned child issues. Use sub-issue links after filing.
      placeholder: |
        - [ ] #123 — Task description
        - [ ] #124 — Task description
        - [ ] Task not yet filed — Description
    validations:
      required: false

  - type: dropdown
    id: product-tool
    attributes:
      label: Product/Tool
      description: Which product or tool does this relate to?
      # Sync with config/products.json + config/tools.json
      options:
        - Dashboard
        - Quotes
        - Customers
        - Invoices
        - Jobs
        - Garments
        - Screens
        - Pricing
        - Work Orchestrator
        - Skills Framework
        - Agent System
        - Knowledge Base
        - CI Pipeline
        - PM System
    validations:
      required: true

  - type: textarea
    id: milestone-context
    attributes:
      label: Milestone context
      description: How does this relate to current milestones or deadlines?
      placeholder: Part of D-Day milestone, needed before Feb 21 demo
    validations:
      required: false
