name: Tracking Issue
description: Track a multi-part effort with sub-issues
title: '[Tracking] '
labels: ['type/tooling']
body:
  - type: markdown
    attributes:
      value: |
        Tracking issues coordinate multi-part efforts. After creating this issue,
        add sub-issues via GitHub's sub-issue feature rather than task-list checkboxes.

  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: What does completion look like?
      placeholder: Describe the end state when all sub-issues are resolved
    validations:
      required: true

  - type: textarea
    id: sub-issues
    attributes:
      label: Sub-issues planned
      description: List planned child issues. Use sub-issue links after filing.
      placeholder: |
        - [ ] #123 — Task description
        - [ ] #124 — Task description
        - [ ] Task not yet filed — Description
    validations:
      required: false

  - type: dropdown
    id: product-domain-tool
    attributes:
      label: Product / Domain / Tool
      description: Which product, domain, or tool does this relate to?
      # Sync with config/products.json + config/tools.json
      options:
        - Product: Dashboard
        - Product: Quotes
        - Product: Customers
        - Product: Invoices
        - Product: Jobs
        - Product: Garments
        - Product: Screens
        - Domain: Garments
        - Domain: Screens
        - Domain: Pricing
        - Domain: Colors
        - Domain: Direct-to-Film
        - Domain: Screen Printing
        - Domain: Mobile
        - Tool: Work Orchestrator
        - Tool: Skills Framework
        - Tool: Agent System
        - Tool: Knowledge Base
        - Tool: CI Pipeline
        - Tool: PM System
      required: true

  - type: textarea
    id: milestone-context
    attributes:
      label: Milestone context
      description: How does this relate to current milestones or deadlines?
      placeholder: Part of D-Day milestone, needed before Feb 21 demo
    validations:
      required: false
